#! /usr/bin/bash

# Aliases & Vars
export CLASSPATH=".:/usr/local/lib/antlr-4.9.2-complete.jar:$CLASSPATH"

# Cleans the project
./clean


# Builds Parser & Lexer
java -jar /usr/local/lib/antlr-4.9.2-complete.jar ./arithLisp.g4 -o srcParserLexer
cd srcParserLexer
javac *.java

# Initializes prompt to test some expressions
java org.antlr.v4.gui.TestRig arithLisp prog -gui